<?php

// autoload_static.php @generated by Composer

namespace Ppfeufer\Plugin\WordPressTweaks\Libs\Composer\Autoload;

class ComposerStaticInit5dc14de0a3ed961632ba26bb0e18c787
{
    public static $files = array (
        'bcc4dbbb6b6e7332bc139fb8b2ed18ad' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/load-v5p6.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Ppfeufer\\Plugin\\WordPressTweaks\\' => 32,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ppfeufer\\Plugin\\WordPressTweaks\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Sources',
        ),
    );

    public static $classMap = array (
        'ComposerAutoloaderInit5dc14de0a3ed961632ba26bb0e18c787' => __DIR__ . '/..' . '/composer/autoload_real.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Parsedown' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/vendor/ParsedownModern.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Interfaces\\TweakInterface' => __DIR__ . '/../../..' . '/Sources/Interfaces/TweakInterface.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\Composer\\Autoload\\ClassLoader' => __DIR__ . '/..' . '/composer/ClassLoader.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\Composer\\Autoload\\ComposerStaticInit5dc14de0a3ed961632ba26bb0e18c787' => __DIR__ . '/..' . '/composer/autoload_static.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Autoloader' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Autoloader.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\DebugBar\\Extension' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/DebugBar/Extension.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\DebugBar\\Panel' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/DebugBar/Panel.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\DebugBar\\PluginExtension' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/DebugBar/PluginExtension.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\DebugBar\\PluginPanel' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/DebugBar/PluginPanel.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\DebugBar\\ThemePanel' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/DebugBar/ThemePanel.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\InstalledPackage' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/InstalledPackage.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Metadata' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Metadata.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\OAuthSignature' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/OAuthSignature.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Plugin\\Package' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Plugin/Package.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Plugin\\PluginInfo' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Plugin/PluginInfo.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Plugin\\Ui' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Plugin/Ui.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Plugin\\Update' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Plugin/Update.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Plugin\\UpdateChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Plugin/UpdateChecker.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\PucFactory' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/PucFactory.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Scheduler' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Scheduler.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\StateStore' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/StateStore.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Theme\\Package' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Theme/Package.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Theme\\Update' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Theme/Update.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Theme\\UpdateChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Theme/UpdateChecker.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Update' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Update.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\UpdateChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/UpdateChecker.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\UpgraderStatus' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/UpgraderStatus.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Utils' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Utils.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\Api' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/Api.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\BaseChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/BaseChecker.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\BitBucketApi' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/BitBucketApi.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\GitHubApi' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/GitHubApi.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\GitLabApi' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/GitLabApi.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\PluginUpdateChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/PluginUpdateChecker.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\Reference' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/Reference.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\ReleaseAssetSupport' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/ReleaseAssetSupport.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\ReleaseFilteringFeature' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/ReleaseFilteringFeature.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\ThemeUpdateChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/ThemeUpdateChecker.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\VcsCheckerMethods' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/VcsCheckerMethods.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\WpCliCheckTrigger' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/WpCliCheckTrigger.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Main' => __DIR__ . '/../../..' . '/Sources/Main.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Settings' => __DIR__ . '/../../..' . '/Sources/Settings.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Singletons\\GenericSingleton' => __DIR__ . '/../../..' . '/Sources/Singletons/GenericSingleton.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks' => __DIR__ . '/../../..' . '/Sources/Tweaks.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\AutoUpdateMails' => __DIR__ . '/../../..' . '/Sources/Tweaks/AutoUpdateMails.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\Canonical' => __DIR__ . '/../../..' . '/Sources/Tweaks/Canonical.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\Emoji' => __DIR__ . '/../../..' . '/Sources/Tweaks/Emoji.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\EnfoldTheme' => __DIR__ . '/../../..' . '/Sources/Tweaks/EnfoldTheme.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\GeneratorName' => __DIR__ . '/../../..' . '/Sources/Tweaks/GeneratorName.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\Links' => __DIR__ . '/../../..' . '/Sources/Tweaks/Links.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\Login' => __DIR__ . '/../../..' . '/Sources/Tweaks/Login.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\Oembed' => __DIR__ . '/../../..' . '/Sources/Tweaks/Oembed.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\Pingback' => __DIR__ . '/../../..' . '/Sources/Tweaks/Pingback.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\VersionStrings' => __DIR__ . '/../../..' . '/Sources/Tweaks/VersionStrings.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\WooCommerce' => __DIR__ . '/../../..' . '/Sources/Tweaks/WooCommerce.php',
        'Ppfeufer\\Plugin\\WordPressTweaks\\Tweaks\\YoutubeEmbed' => __DIR__ . '/../../..' . '/Sources/Tweaks/YoutubeEmbed.php',
        'PucReadmeParser' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/vendor/PucReadmeParser.php',
        'WPSFTest' => __DIR__ . '/..' . '/iconicwp/wpsf/wpsf-test.php',
        'WordPressSettingsFramework' => __DIR__ . '/..' . '/iconicwp/wpsf/wp-settings-framework.php',
        'YahnisElsts\\PluginUpdateChecker\\v5\\PucFactory' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5/PucFactory.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5dc14de0a3ed961632ba26bb0e18c787::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5dc14de0a3ed961632ba26bb0e18c787::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5dc14de0a3ed961632ba26bb0e18c787::$classMap;

        }, null, ClassLoader::class);
    }
}
