<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit5dc14de0a3ed961632ba26bb0e18c787
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Ppfeufer\Plugin\WordPressTweaks\Libs\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Ppfeufer\Plugin\WordPressTweaks\Libs\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit5dc14de0a3ed961632ba26bb0e18c787', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Ppfeufer\Plugin\WordPressTweaks\Libs\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit5dc14de0a3ed961632ba26bb0e18c787', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Ppfeufer\Plugin\WordPressTweaks\Libs\Composer\Autoload\ComposerStaticInit5dc14de0a3ed961632ba26bb0e18c787::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \Ppfeufer\Plugin\WordPressTweaks\Libs\Composer\Autoload\ComposerStaticInit5dc14de0a3ed961632ba26bb0e18c787::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
