<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'bcc4dbbb6b6e7332bc139fb8b2ed18ad' => $vendorDir . '/yahnis-elsts/plugin-update-checker/load-v5p6.php',
);
